### PR TITLE
Export logs as wercker artifacts and delete e2e namespace on test failure

### LINKED ISSUE #177: Export logs in E2E tests
Currently, we debug failed E2E tests by skipping deletion of the specific test namespace on failure thereby leaving the resources available for inspection. This will no longer apply to all users once third-party developers can trigger CI via pull requests.

We should delete namespaces even on failure and export the following logs as artefacts of the pipeline:

 - MySQL Operator container logs
 - All MySQL server instances
 - All mysql-agent instances

Related: #97

### PR DESCRIPTION
**Pull request by harveylowndes**
Closes #177 

MySQL Agent, Server and Operator logs will be exported as wercker artifacts on a per pod basis. If tests are run locally they are printed to stdout. E2E test namespace deletion follows regardless of whether the test passes or fails.

### CODE REVIEW

File: test/e2e/framework/framework.go [hunk 1]
```diff
@@ -248,6 +250,8 @@ func (f *Framework) BeforeEach() {
 func (f *Framework) AfterEach() {
 	RemoveCleanupAction(f.cleanupHandle)
 
+	printMySQLPodContainerLogs(f)
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: Needs a more accurate name. It's not printing, mysql pod container logs, it's retrieving, storing, dumping all container logs really...

File: test/e2e/framework/framework.go [hunk 2]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
 	}
 	f.OperatorInstalled = false
 }
+
+func printMySQLPodContainerLogs(f *Framework) {
```
Comment (prydie) [inline test/e2e/framework/framework.go]:
```go
 func (f *Framework) outputLogs() error
```

File: test/e2e/framework/framework.go [hunk 3]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+	pods, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).List(metav1.ListOptions{})
+	if err != nil {
+		Logf("Error retrieving pod list in namespace %s: %+v", f.Namespace.Name, err)
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: Shouldn't we bomb out here, return an error or something instead of logging and continuing

Comment (prydie) [inline test/e2e/framework/framework.go]:
```go
return errors.Wrap(err, "listing test Pods")
```

(otherwise `pods.Items` will panic below if the above fails)

File: test/e2e/framework/framework.go [hunk 4]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+
+func printLogs(read io.ReadCloser, fileName string) error {
+	defer read.Close()
+	env := os.Getenv("WERCKER_REPORT_ARTIFACTS_DIR")
+	dst := os.Stdout
+	if env != "" {
+		filepath := env + "/" + fileName + ".log"
+		file, err := os.OpenFile(filepath, os.O_WRONLY|os.O_CREATE, 0666)
+		if err != nil {
+			return fmt.Errorf("Error getting file for logs: %+v", err)
```
Comment (prydie) [inline test/e2e/framework/framework.go]:
```go
return errors.Wrapf(err, "opening log file %q", filepath)
```

File: test/e2e/framework/framework.go [hunk 5]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+			opPod = pod
+			continue
+		}
+		if strings.Contains(pod.Spec.Containers[0].Image, "mysql-agent") || strings.Contains(pod.Spec.Containers[0].Image, "mysql-server") {
+			agPods = append(agPods, pod)
+		}
+	}
+
+	// Operator Logs
+	if opPod.Name != "" {
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: Probably need else block to handle opPod.Name being empty?

File: test/e2e/framework/framework.go [hunk 6]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+
+	for _, agPod := range agPods {
+		// Server Logs
+		printContainerLogs(f, agPod.GetName(), &v1.PodLogOptions{Container: "mysql"})
+		// Agent Logs
+		printContainerLogs(f, agPod.GetName(), &v1.PodLogOptions{Container: "mysql-agent"})
+	}
+}
+
+func printLogs(read io.ReadCloser, fileName string) error {
```
Comment (prydie) [inline test/e2e/framework/framework.go]: Pass in full file path and load `os.Getenv("WERCKER_REPORT_ARTIFACTS_DIR")` on `Framework` initialisation

File: test/e2e/framework/framework.go [hunk 7]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+	defer read.Close()
+	env := os.Getenv("WERCKER_REPORT_ARTIFACTS_DIR")
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: needs a better name

File: test/e2e/framework/framework.go [hunk 8]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+	dst := os.Stdout
+	if env != "" {
+		filepath := env + "/" + fileName + ".log"
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: Would be nice to use os.Separator here instead of "/", maybe use a fmt.Sprintf too

Comment (prydie) [inline test/e2e/framework/framework.go]: Needs moving as per above but:

```go
filePath := path.Join(env, fmt.Sprintf("%s.log", fileName))
```

File: test/e2e/framework/framework.go [hunk 9]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+		file, err := os.OpenFile(filepath, os.O_WRONLY|os.O_CREATE, 0666)
+		if err != nil {
+			return fmt.Errorf("Error getting file for logs: %+v", err)
+		}
+		dst = file
+		defer dst.Close()
+	}
+	_, err := io.Copy(dst, read)
+	if err != nil {
+		return fmt.Errorf("Error exporting logs: %+v", err)
```
Comment (prydie) [inline test/e2e/framework/framework.go]:
```go
return errors.Wrapf(err, "writing logs to %q", filepath)
```

File: test/e2e/framework/framework.go [hunk 10]
```diff
@@ -272,3 +276,64 @@ func (f *Framework) AfterEach() {
...
+	}
+	return nil
+}
+
+func printContainerLogs(f *Framework, podName string, options *v1.PodLogOptions) {
+	podLogs := f.ClientSet.CoreV1().Pods(f.Namespace.Name).GetLogs(podName, options)
+	if podLogs != nil {
+		Logf("Writing %s container logs to file for %s", options.Container, podName)
+		read, _ := podLogs.Stream()
```
Comment (simonlord) [inline test/e2e/framework/framework.go]: what is _ in this case? If it's an error we can't ignore it...

File: test/e2e/framework/framework.go (hunk 1 above)
Comment (prydie) [inline test/e2e/framework/framework.go]:
```go
if err := f.outputLogs(); err != nil {
	Logf("Failed to output container logs: %v", err)
}
```
