### PR TITLE
Add BackupOperator UpdateFunc and fix duplicate backups

### LINKED ISSUE #211: Questions with 2 TODO comments
Not sure whether the next 2 TODOs are still valid or not? @prydie 

In agent controller, there is a `UpdateFunc` already added for `backupInformer` as below.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/agent_controller.go#L126-L128

so this todo may no longer need?
https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/agent_controller.go#L281-L283

same for the operator controller side? my tests showed fixing validation error by running `kubectl apply -f` with correct backup.yaml works good.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/operator_controller.go#L257-L258

### PR DESCRIPTION
**Pull request by Simon-Li**
fix #211 , #212

### CODE REVIEW

File: pkg/controllers/backup/agent_controller.go [hunk 1]
```diff
@@ -342,6 +354,16 @@ func (controller *AgentController) performBackup(backup *v1alpha1.Backup, creds
...
 
+	// Get (updated) resource from store.
+	backup, err = controller.backupLister.Backups(backup.GetNamespace()).Get(backup.GetName())
+	if err != nil {
+		return errors.Wrap(err, "error getting Backup")
+	}
+	// Don't modify items in the cache.
+	backup = backup.DeepCopy()
+	// Set defaults (incl. operator version label).
+	backup = backup.EnsureDefaults()
```
Comment (bweston92) [inline pkg/controllers/backup/agent_controller.go]: Can this not just be?

```
backup = backup.DeepCopy().EnsureDefaults()
```

Comment (Simon-Li) [reply pkg/controllers/backup/agent_controller.go]: Yep, it's fine :) @bweston92
